### ISSUE TITLE
Building SGX modules for 3.8.x

### ISSUE THREAD

**Issue by fernandorocha** [RobertCNelson/stable-kernel#25]
Hello Robert,
I was trying to build the sgx modules but seems that the sgx SDK version does not support the 3.8 kernel, as it tries to include a file that has been moved on the 3.7 -> 3.8 change.
I got the following:
ti-sdk-pvr/Graphics_SDK/GFX_Linux_KM/services4/3rdparty/dc_omapfb3_linux/omaplfb_linux.c:111:23: fatal error: plat/vrfb.h: No such file or directory.

I think it is pointing to: KERNEL/arch/arm/plat-omap/include/plat/vrfb.h

existing on 3.7 but on 3.8 this file does not exist, but a very very similar file is at: KERNEL/include/video/omapvrfb.h

Is the 4.08.00.02 version of the SDK compatible with the kernel 3.8?
If not, is it possible to just change the versions variables on the build_sgx_modules script so it uses the 4.09.00.01?

Thank you very much.
Fernando Rocha

**Comment by addev72000** [comment]
Hello,

I have the same issue with kernel 4.1.10, how to solve it ?

[   78.971271] omaplfb: Unknown symbol register_vsync_cb (err 0)
[   78.977388] omaplfb: Unknown symbol unregister_vsync_cb (err 0)
[   79.043430] Unable to handle kernel NULL pointer dereference at virtual address 00000000
[   79.051589] pgd = dcb9c000

Thank you for the feeb back,

**Comment by RobertCNelson** [comment]
@addev72000 totally different issue:

Please create a new thread

https://groups.google.com/forum/#!forum/beagleboard

and include your full "uname -r"

Regards,
